fixed wakeonlan path for apple silicon

diff --git a/start_elstar b/start_elstar
--- a/start_elstar
+++ b/start_elstar
@@ -11,7 +11,14 @@ TRIES=0
 # max tries (30sec / try)
 MAX_TRIES=20
 
-/usr/local/bin/wakeonlan -i $BROADCAST_IP $SERVER_MAC
+if [ -f "/usr/local/bin/wakeonlan" ]; then
+  /usr/local/bin/wakeonlan -i $BROADCAST_IP $SERVER_MAC
+elif [ -f "/opt/homebrew/bin/wakeonlan" ]; then
+  /opt/homebrew/bin/wakeonlan -i $BROADCAST_IP $SERVER_MAC
+else 
+  echo "wakonlan executable not found, exiting..."
+  exit 1
+fi
 
 while (( TRIES < MAX_TRIES ))
 do
